# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38fe76b111b3c69bbef3a13f65c4f95db0a46b09b278fc8d8034dc005db46b52e9eb7c510cc77eb9ca81848ea32ccda4215ee245ee49ddf739f26510e4e2515

test:
  secret_key_base: eb8c4e6017ae4276bd7a9d1177c4f9e22ef48f17caa97c6557d5baa60dbd24edaeedf102d899c53d6a4e536c0a193550d8d9fbd696601251ee37af7825a7e72f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
